# Generated by Django 5.0.6 on 2024-07-01 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('GuardianID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('RelationshipToPatient', models.CharField(max_length=255)),
                ('Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('MedicalHistory', models.TextField()),
                ('GuardianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=255)),
                ('MedicationName', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('Frequency', models.CharField(max_length=255)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Notes', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Status', models.CharField(max_length=255)),
                ('Notes', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.patient')),
                ('PrescriptionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.prescription')),
            ],
        ),
    ]
