# Generated by Django 5.0.6 on 2024-07-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='Email',
            new_name='UserID',
        ),
    ]
