# Generated by Django 5.0.6 on 2024-07-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0003_remove_prescriptionlog_patientid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('BloodType', models.CharField(max_length=3)),
                ('GuardianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Condition', models.CharField(max_length=255)),
                ('DoctorName', models.CharField(max_length=255)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicationName', models.CharField(max_length=255)),
                ('Label', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('NotificationTime', models.TimeField()),
                ('Frequency', models.CharField(max_length=255)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('PrescriptionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='healthcare_app.prescription')),
            ],
        ),
    ]
