# Generated by Django 5.0.6 on 2024-07-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0004_patient_prescription_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BloodType',
            field=models.CharField(max_length=5),
        ),
    ]
